version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - sam build
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - template.yaml